path: './'
http:
  address: ':80'
urls:
  a0: https://hackmd.io/ByVt9CthSPWLOIdiH4vcrA?edit
  a1: https://hackmd.io/89pKVHEGQxOzh3TbOtEfEw?edit
  a2: https://hackmd.io/Rl8ToCoUQ6Gvqq_dUkFP9w?edit
disableMetaFetch: false
